name: Manual Action

on:
  workflow_dispatch:
    inputs:
      command_line:
        description: 'some command line'
        required: true
        default: 'npm --version'
      message:
        description: 'some echo'
        required: false
        default: '' 


jobs:
  test:
    name: Running Npm Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: step 1 install 
      run: npm install
    
    - name: step 2 test
      run: npm test

    - name: step 3 custom command
      run: ${{github.event.inputs.command_line}}

    - name: step 4 check branch
      run: git branch --show-current

    - name: step 5 echo 
      run: echo ${{github.event.inputs.message}}
